version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_DB=shopping_cart
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=shopping_cart
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
